<?php
// Register Custom Post Type for Cities
function register_cities_cpt() {
    $args = array(
        'label'                 => __( 'Cities', 'text_domain' ),
        'description'           => __( 'Custom post type for cities', 'text_domain' ),
        'labels'                => array(
            'name'                  => _x( 'Cities', 'Post Type General Name', 'text_domain' ),
            'singular_name'         => _x( 'City', 'Post Type Singular Name', 'text_domain' ),
            'menu_name'             => __( 'Cities', 'text_domain' ),
            'name_admin_bar'        => __( 'City', 'text_domain' ),
            'archives'              => __( 'City Archives', 'text_domain' ),
            'attributes'            => __( 'City Attributes', 'text_domain' ),
            'parent_item_colon'     => __( 'Parent City:', 'text_domain' ),
            'all_items'             => __( 'All Cities', 'text_domain' ),
            'add_new_item'          => __( 'Add New City', 'text_domain' ),
            'add_new'               => __( 'Add New', 'text_domain' ),
            'new_item'              => __( 'New City', 'text_domain' ),
            'edit_item'             => __( 'Edit City', 'text_domain' ),
            'update_item'           => __( 'Update City', 'text_domain' ),
            'view_item'             => __( 'View City', 'text_domain' ),
            'view_items'            => __( 'View Cities', 'text_domain' ),
            'search_items'          => __( 'Search City', 'text_domain' ),
            'not_found'             => __( 'Not found', 'text_domain' ),
            'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
            'featured_image'        => __( 'Featured Image', 'text_domain' ),
            'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
            'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
            'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
            'insert_into_item'      => __( 'Insert into city', 'text_domain' ),
            'uploaded_to_this_item' => __( 'Uploaded to this city', 'text_domain' ),
            'items_list'            => __( 'Cities list', 'text_domain' ),
            'items_list_navigation' => __( 'Cities list navigation', 'text_domain' ),
            'filter_items_list'     => __( 'Filter cities list', 'text_domain' ),
        ),
        'supports'              => array( 'title' ),
        'hierarchical'          => false,
        'public'                => true,
        'show_ui'               => true,
        'show_in_menu'          => true,
        'menu_position'         => 5,
        'show_in_admin_bar'     => true,
        'show_in_nav_menus'     => true,
        'can_export'            => true,
        'has_archive'           => false,
        'exclude_from_search'   => false,
        'publicly_queryable'    => true,
        'capability_type'       => 'post',
    );
    register_post_type( 'cities', $args );
}
add_action( 'init', 'register_cities_cpt', 0 );
